name = 'gongo'
main = 'src/server/worker.ts'
compatibility_date = '2026-07-17'
compatibility_flags = ['nodejs_compat']
workers_dev = false
preview_urls = false
routes = [{ pattern = 'gongo.tv', custom_domain = true }]

[assets]
binding = 'ASSETS'
not_found_handling = 'single-page-application'
run_worker_first = [
	'/b2/*',
	'/notification/*',
	'/osmo',
	'/r2/*',
	'/rss/*',
	'/stream/direct',
	'/stream/info',
	'/stream/m3u',
	'/stream/m3u8',
	'/stream/xmltv',
	'/vods/list',
	'/vods/thumbnail/*',
	'/.well-known/did.json',
	'/xrpc/app.bsky.feed.describeFeedGenerator',
	'/xrpc/app.bsky.feed.getFeedSkeleton'
]

[browser]
binding = 'BROWSER'
remote = true

[cache]
enabled = true

[durable_objects]
bindings = [{ name = 'CALLOFTHEGONGO', class_name = 'Notifications' }]

[exports]
Notifications = { type = 'durable-object', storage = 'sqlite' }

[[kv_namespaces]]
binding = 'CONFIG'
id = '4e0458fae76f460f88bee380c18be69d'

[[kv_namespaces]]
binding = 'THUMBNAILS'
id = '364658ec89a6473fb2bbe76bdb507bf0'
remote = true

[observability]
logs = { enabled = true }

[placement]
hostname = 's3.eu-central-003.backblazeb2.com'

[[r2_buckets]]
binding = 'R2'
bucket_name = 'gongo'
remote = true

[secrets]
required = ['B2_APPLICATION_KEY', 'SMTP_PASSWORD', 'TWITCH_CLIENT_SECRET', 'VAPID_PRIVATE_KEY']

[vars]
B2_APPLICATION_KEY_ID = '00348459c62c8d40000000007'
B2_ENDPOINT = 's3.eu-central-003.backblazeb2.com'
B2_BUCKET_NAME = 'gongos'
FRESHRSS_USERNAME = 'root'
FRESHRSS_QUERY_TOKEN = '3I0QvV6LCOaYmkf8WKgFpr'
SMTP_USERNAME = 'notifications@gongo.tv'
SMTP_SERVER = 'smtp.protonmail.ch'
SMTP_PORT = 587
TWITCH_CLIENT_ID = '1ao3j6d7bndjeovhkrfgb6tdkcwg62'
VAPID_PUBLIC_KEY = 'BIs_XyzFXw8YdSbwrUY2AyxboSm7dUsWf3__WIFNR0OYX_SBsHmQQr75ujLdm2577i_2YcIovKOlsPXq-kT_WL0'
VAPID_SUBJECT = 'https://gongo.tv/stream'

[[vpc_services]]
binding = 'FRESHRSS'
service_id = '019fe31d-5e26-7be2-b585-7916cb15fcda'
remote = true

[[vpc_services]]
binding = 'GONGSKY'
service_id = '019fe31c-a67a-7180-96d2-8d4e1d1d4905'
remote = true
