name = 'gongo'
main = 'src/server/worker.ts'
compatibility_date = '2026-07-17'
compatibility_flags = ['nodejs_compat']
workers_dev = true
preview_urls = false
# routes = [{ pattern = 'gongo.live', custom_domain = true }]

[assets]
binding = 'ASSETS'
not_found_handling = 'single-page-application'
run_worker_first = [
	'/api/*',
	'/b2/*',
	'/livestreams',
	'/notification/*',
	'/osmo',
	'/r2/*',
	'/rss/*',
	'/stream/direct',
	'/stream/m3u',
	'/stream/m3u8',
	'/stream/xmltv',
	'/token',
	'/vods/list',
	'/vods/thumbnail/*',
	'/.well-known/did.json',
	'/xrpc/app.bsky.feed.describeFeedGenerator',
	'/xrpc/app.bsky.feed.getFeedSkeleton'
]

[browser]
binding = 'ANGELTHUMP'
remote = true

[cache]
enabled = true

[durable_objects]
bindings = [{ name = 'CALLOFTHEGONGO', class_name = 'Notifications' }]

[[migrations]]
tag = 'v1'
new_sqlite_classes = ['Notifications']

[[kv_namespaces]]
binding = 'CONFIG'
id = '3ac23e7ab2624152bb0e5ac19a031d21'

[[kv_namespaces]]
binding = 'THUMBNAILS'
id = 'bf592eb0c8ad4e31b6ee107d791d3f73'
remote = true

[observability]
logs = { enabled = true }

[placement]
hostname = 's3.eu-central-003.backblazeb2.com'

[[r2_buckets]]
binding = 'R2'
bucket_name = 'gongo'
remote = true

[secrets]
required = ['B2_APPLICATION_KEY', 'SMTP_PASSWORD', 'TWITCH_CLIENT_SECRET', 'VAPID_PRIVATE_KEY']

[[services]]
binding = 'COMPUTER'
service = 'computer'
remote = true

[vars]
B2_APPLICATION_KEY_ID = '00348459c62c8d40000000007'
B2_ENDPOINT = 's3.eu-central-003.backblazeb2.com'
B2_BUCKET_NAME = 'gongos'
FRESHRSS_USERNAME = 'root'
FRESHRSS_QUERY_TOKEN = '3I0QvV6LCOaYmkf8WKgFpr'
SMTP_USERNAME = 'notifications@bergbok.computer'
SMTP_SERVER = 'smtp.protonmail.ch'
SMTP_PORT = 587
TWITCH_CLIENT_ID = '1ao3j6d7bndjeovhkrfgb6tdkcwg62'
VAPID_PUBLIC_KEY = 'BIs_XyzFXw8YdSbwrUY2AyxboSm7dUsWf3__WIFNR0OYX_SBsHmQQr75ujLdm2577i_2YcIovKOlsPXq-kT_WL0'
VAPID_SUBJECT = 'https://gongo.bergbok.workers.dev/stream'

[[vpc_services]]
binding = 'FRESHRSS'
service_id = '019f89b1-9d93-7231-8a64-dc2543d7cfcf'
remote = true

[[vpc_services]]
binding = 'GONGSKY'
service_id = '019f8e3c-e209-7740-921b-9694f1f21383'
remote = true
